(define (pow x y)
  (define (iter x y result)
    (cond ((= y 0) result)
	  ((even? y) (iter (* x x) (/ y 2) result))
	  (else (iter x (- y 1) (* x result)))))
  (iter x y 1))
(define (digit-sum num)
  (define (iter num result)
    (cond ((= num 0) result)
	  (else (iter (quotient num 10) (+ result (remainder num 10))))))
  (iter num 0))
(digit-sum (pow 2 1000))
