(define (digit-sum num)
  (define (iter num result)
    (cond ((= num 0) result)
	  (else (iter (quotient num 10) (+ result (remainder num 10))))))
  (iter num 0))
(define (fact n)
  (define (iter n acc)
    (if (= n 0) acc (iter (- n 1) (* acc n))))
  (iter n 1))
(digit-sum (fact 100))
