(define (pow x y)
  (define (iter x y result)
    (cond ((= y 0) result)
	  ((even? y) (iter (* x x) (/ y 2) result))
	  (else (iter x (- y 1) (* x result)))))
  (iter x y 1))
(define (fib limit)
  (define (iter n n1 n2)
    (if (>= n1 limit) n (iter (+ n 1) (+ n1 n2) n1)))
  (iter 1 1 0))
(fib (pow 10 999))
